### ISSUE TITLE
Make it portable

### ISSUE THREAD

**Issue by papuashu** [abatishchev/IFactory#2]
When adding the NuGet packages (IFactory and IFactory.SimpleInjector) to a portable project I get the error in output window:
Could not install package 'IFactory 0.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile344', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thanks in advance.

**Comment by abatishchev** [comment]
I never worked with portable projects and don't have experience of producing a portable nuget package. 

Do you have any ideas how to do it? If you could submit a PR I would merge it right away.
I think we can clone the approach of [SimpleInjector](https://github.com/simpleinjector/SimpleInjector/tree/master/src) or [FluentValidation](https://github.com/JeremySkinner/FluentValidation/tree/master/src).

**Comment by abatishchev** [comment]
I'm going to port this to Core
